load("@pybind11_bazel//:build_defs.bzl", "pybind_library")

pybind_library(
    name = "utilities",
    srcs = ["arithmetic.cpp"],
    hdrs = ["arithmetic.hpp"],
    visibility = ["//visibility:public"],
)
